domino:
  logging:
    min-level: info
    enable-json-logging: true
  test-node:
    key1: value1
    map-node:
      key3: value3
      key4: value4
    list-node:
      - key5: value5
        key6: value6
