version: 2.1

orbs:
  jira: circleci/jira@2.1.0
  node: circleci/node@5.2.0
  jq: circleci/jq@3.0.0
  gh: circleci/github-cli@2.3.0

# Common parameters for CircleCI build config
parameters:
  run-domino-platform-coordinator-release:
    type: boolean
    default: false
  run-domino-platform-docker-agent-release:
    type: boolean
    default: false
  run-domino-platform-coordinator-rc:
    type: boolean
    default: false
  run-domino-platform-docker-agent-rc:
    type: boolean
    default: false
  run-domino-platform-binary-executable-agent-release:
    type: boolean
    default: false
  distribution_source_dir:
    type: string
    default: dist/
  distribution_archive_prefix:
    type: string
    default: domino-platform-
  distribution_archive_extension:
    type: string
    default: .tar.gz
  workspace_dir:
    type: string
    default: /tmp/ws_store
  version_file:
    type: string
    default: version

# Reusable commands
commands:

  # Command definition for publishing GitHub releases/tags
  github_release:
    parameters:
      release-type:
        type: enum
        default: "rc"
        enum: ["rc", "release"]
      module:
        type: enum
        enum: ["coordinator", "docker-agent", "binary-executable-agent"]
    steps:
      - checkout
      - attach_workspace:
          at: << pipeline.parameters.workspace_dir >>
      - gh/setup
      - run:
          name: "Publish Release on GitHub"
          command: |
            [[ "<< parameters.release-type >>" = "release" ]] && VERSION_QUALIFIER=".release" || VERSION_QUALIFIER=""
            VERSION=<< parameters.module >>-v$(cat << pipeline.parameters.workspace_dir >>/<< parameters.module >>_<< pipeline.parameters.version_file >>)$VERSION_QUALIFIER
            gh release create ${VERSION} --target ${CIRCLE_SHA1} --title ${VERSION} << pipeline.parameters.workspace_dir >>/<< pipeline.parameters.distribution_archive_prefix >><< parameters.module >><< pipeline.parameters.distribution_archive_extension >>

  # Command definition for publishing GitHub releases/tags
  github_executable_release:
    parameters:
      module:
        type: enum
        enum: ["binary-executable-agent"]
    steps:
      - checkout
      - attach_workspace:
          at: << pipeline.parameters.workspace_dir >>
      - gh/setup
      - run:
          name: "Publish executable release on GitHub"
          command: |
            VERSION_LABEL=<< parameters.module >>-linux-x64-v$(cat << pipeline.parameters.workspace_dir >>/<< parameters.module >>_<< pipeline.parameters.version_file >>)-release
            gh release create ${VERSION_LABEL} --target ${CIRCLE_SHA1} --title ${VERSION_LABEL} << pipeline.parameters.workspace_dir >>/dist/domino-<< parameters.module >>

executors:
  node:
    docker:
      - image: cimg/node:22.12.0
  base:
    docker:
      - image: cimg/base:stable

jobs:

  # Domino Platform - Build and test application
  build:
    parameters:
      release-type:
        type: enum
        default: "rc"
        enum: ["rc", "release"]
      module:
        type: enum
        enum: ["coordinator", "docker-agent", "binary-executable-agent"]
      distributable-type:
        type: enum
        enum: ["docker", "executable"]
    executor: node
    steps:
      - checkout
      - run:
          name: Displaying module to be built
          command: |
            echo "Switching to module << parameters.module >>"
      - run:
          name: Set build number
          command: |
            case $CIRCLE_BRANCH in
              master) echo 'export BUILD_NUMBER="rc.<< pipeline.number >>"' >> $BASH_ENV ;;
              deploy) echo 'export BUILD_NUMBER=$((`git fetch --tags && git tag --sort=-taggerdate | grep release | grep << parameters.module >> | sed -E "s/<< parameters.module >>-v[0-9]+\.[0-9]+\.[0-9]+\-([0-9]+)\.release/\1/" | sort -nr | head -n 1` + 1))' >> $BASH_ENV ;;
              *) echo 'export BUILD_NUMBER="snapshot"' >> $BASH_ENV ;;
            esac
            source $BASH_ENV
            echo "Determined BUILD_NUMBER=$BUILD_NUMBER"
      - run:
          name: Extract version number
          command: |
            cd ./modules/<< parameters.module >>
            source $BASH_ENV
            BASE_VERSION=$(cat package.json | grep version | head -n 1 | sed -E "s/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/")
            VERSION=$BASE_VERSION-$BUILD_NUMBER
            echo "Extracted version $VERSION"
            echo "export VERSION='$VERSION'" >> $BASH_ENV
            mkdir << pipeline.parameters.workspace_dir >>
            echo $VERSION >> << pipeline.parameters.workspace_dir >>/<< parameters.module >>_<< pipeline.parameters.version_file >>
      - run:
          name: Install NPM dependencies
          command: |
            npm install --workspaces=false
            if [[ "<< parameters.module >>" = "docker-agent" || "<< parameters.module >>" = "binary-executable-agent" ]]; then
              npm install --workspace=@domino-platform/agent-core
            fi
            npm install --workspace=@domino-platform/platform-core --workspace=@domino-platform/<< parameters.module >>
      - run:
          name: Update project version
          command: |
            npm config set git-tag-version false
            npm version $VERSION --workspace=@domino-platform/<< parameters.module >>
      - run:
          name: Execute Domino Platform unit tests
          command: |
            mkdir logs
            npm run test --workspace=@domino-platform/platform-core --workspace=@domino-platform/agent-core --workspace=@domino-platform/<< parameters.module >>
      - run:
          name: Transpile code
          command: |
            npm run build --workspace=@domino-platform/<< parameters.module >>
      - run:
          name: Clean-up node_modules
          command: npm prune --omit=dev
      - setup_remote_docker
      - run:
          name: Package and upload Docker image
          command: |
            
            if [[ "<< parameters.distributable-type >>" = "executable" ]]; then
              echo "Skipping Docker build for << parameters.module >>"
              exit 0
            fi
            
            source $BASH_ENV
            
            docker login ${LEAFLET_DOCKER_REGISTRY_HOST} \
              --username ${LEAFLET_DOCKER_REGISTRY_USERNAME} \
              --password ${LEAFLET_DOCKER_REGISTRY_PASSWORD}

            version_tag=${LEAFLET_DOCKER_REGISTRY_HOST}/domino-platform/<< parameters.module >>:${VERSION}
            docker build --build-arg APP_HOME=/opt/<< parameters.module >> --build-arg APP_EXECUTABLE=dist/<< parameters.module >>-main.js --tag $version_tag .
            docker push $version_tag

            if [[ "<< parameters.release-type >>" = "release" ]]; then
              latest_tag=${LEAFLET_DOCKER_REGISTRY_HOST}/domino-platform/<< parameters.module >>:latest
              docker tag $version_tag $latest_tag
              docker push $latest_tag
            fi
      - run:
          name: Package into executable
          command: |
            
            if [[ "<< parameters.distributable-type >>" = "docker" ]]; then
              echo "Skipping executable build for << parameters.module >>"
              exit 0
            fi
            
            source $BASH_ENV
            
            npm run package --workspace=@domino-platform/<< parameters.module >>
            mkdir << pipeline.parameters.workspace_dir >>/dist
            cp dist/domino-<< parameters.module >> << pipeline.parameters.workspace_dir >>/dist/domino-<< parameters.module >>
            rm dist/domino-<< parameters.module >>

      - run:
          name: Archive dist code
          command: |
            tar -czvf << pipeline.parameters.workspace_dir >>/<< pipeline.parameters.distribution_archive_prefix >><< parameters.module >><< pipeline.parameters.distribution_archive_extension >> << pipeline.parameters.distribution_source_dir >>
      - persist_to_workspace:
          root: << pipeline.parameters.workspace_dir >>
          paths:
            - dist/*
            - << pipeline.parameters.distribution_archive_prefix >><< parameters.module >><< pipeline.parameters.distribution_archive_extension >>
            - << parameters.module >>_<< pipeline.parameters.version_file >>

  # Domino Platform - Publish tag (and release) on GitHub for RELEASE versions
  publish-github-release:
    executor: base
    parameters:
      module:
        type: enum
        enum: ["coordinator", "docker-agent", "binary-executable-agent"]
    steps:
      - github_release:
          module: << parameters.module >>
          release-type: release

  # Domino Platform - Publish the executable binary package for modules packaged in that way
  publish-github-executable-release:
    executor: base
    parameters:
      module:
        type: enum
        enum: [ "binary-executable-agent" ]
    steps:
      - github_executable_release:
          module: << parameters.module >>

workflows:

  # Domino Platform - Build pipeline for Domino Coordinator
  domino-platform-coordinator-release:
    when: << pipeline.parameters.run-domino-platform-coordinator-release >>
    jobs:

      - build:
          module: coordinator
          release-type: release
          distributable-type: docker
          context: leaflet_ci
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

      - release-approval:
          type: approval
          requires:
            - build

      - publish-github-release:
          context: leaflet_ci
          module: coordinator
          requires:
            - release-approval

  # Domino Platform - Build pipeline for Domino Coordinator (RC, build only)
  domino-platform-coordinator-rc:
    when: << pipeline.parameters.run-domino-platform-coordinator-rc >>
    jobs:

      - build:
          module: coordinator
          release-type: rc
          distributable-type: docker
          context: leaflet_ci
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

  # Domino Platform - Build pipeline for Domino Docker Agent
  domino-platform-docker-agent-release:
    when: << pipeline.parameters.run-domino-platform-docker-agent-release >>
    jobs:

      - build:
          module: docker-agent
          release-type: release
          distributable-type: docker
          context: leaflet_ci
          post-steps:
            - jira/notify:
                environment: production
                environment_type: production
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

      - release-approval:
          type: approval
          requires:
            - build

      - publish-github-release:
          context: leaflet_ci
          module: docker-agent
          requires:
            - release-approval

  # Domino Platform - Build pipeline for Domino Docker Agent (RC, build only)
  domino-platform-docker-agent-rc:
    when: << pipeline.parameters.run-domino-platform-docker-agent-rc >>
    jobs:

      - build:
          module: docker-agent
          release-type: rc
          distributable-type: docker
          context: leaflet_ci
          post-steps:
            - jira/notify:
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

  # Domino Platform - Build pipeline for Domino Binary Executable Agent
  domino-platform-binary-executable-agent-release:
    when: << pipeline.parameters.run-domino-platform-binary-executable-agent-release >>
    jobs:

      - build:
          module: binary-executable-agent
          release-type: release
          distributable-type: executable
          context: leaflet_ci
          post-steps:
            - jira/notify:
                environment: production
                environment_type: production
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

      - release-approval:
          type: approval
          requires:
            - build

      - publish-github-release:
          context: leaflet_ci
          module: binary-executable-agent
          requires:
            - release-approval

      - publish-github-executable-release:
          context: leaflet_ci
          module: binary-executable-agent
          requires:
            - publish-github-release

  version: 2
