# Domino Coordinator configuration
domino:

  # Server settings
  server:

    # Server context path (API base path)
    context-path: /

    # Server address to listen on
    host: 0.0.0.0

    # Port to listen on
    port: 9987

  # SQLite datasource settings
  datasource:

    # Path to the SQLite database file
    sqlite-datafile-path: ./data/database.sqlite

    # Enables importing static deployment definitions on application start up
    enable-auto-import: true

  # Logging settings
  logging:

    # Minimum logging level (defaults to 'info' if not specified)
    min-level: info

    # Enables formatting the log messages as JSON
    enable-json-logging: false

  # Data encryption settings
  # Current implementation supports RSA key pair based encryption.
  encryption:

    # Enable/disable encryption of secrets
    # WARNING: Keeping sensitive information unencrypted at rest is considered a highly unsafe practice. If you do plan
    # on using Domino's secret manager, please consider enabling encryption and provide an RSA key pair below
    enabled: false

    # Path to RSA public key in .pem format (for encryption)
    public-key-path: <PROVIDE_ME>

    # Path to RSA private key in .pem format (for decryption)
    private-key-path: <PROVIDE_ME>

  # Management account / OAuth authentication configuration
  auth:

    # Authorization mode
    # direct: access token can be claimed by calling Domino's /claim-token endpoint (legacy)
    # oauth: access token is provided by an external OAuth 2.0 Authorization Server (see oauth-issuer and oauth-audience parameters)
    auth-mode: direct

    # Authentication JWT token expiration (in ms (https://github.com/zeit/ms#readme) utility compatible format)
    expiration: 30 days

    # JWT signing private key
    jwt-private-key: <PROVIDE_ME>

    # Management account username
    username: <PROVIDE_ME>

    # Management account password;
    # Password must be provided in BCrypt encoded format. (Domino CLI provides utility for password encryption.)
    password: <PROVIDE_ME>

    # OAuth 2.0 Authorization Server address for access token verification;
    # The specified server must have a /.well-known/oauth-authorization-server discovery endpoint.
    oauth-issuer: <PROVIDE_ME>

    # OAuth audience value of Domino;
    # The access token used against Domino must have the same audience as specified here.
    oauth-audience: <PROVIDE_ME>

  # Agent configuration
  agent:

    # Maximum amount of time to wait for an agent to respond to a lifecycle request (in ms time string format)
    operation-timeout: 90 sec

    # API key for agent authorization
    api-key: <PROVIDE_ME>

    # Agent registrations
    known-agents:

        # Defined ID of the host the agent is running on.
      - host-id: localhost

        # Deployment type the agent is capable of handling. Currently supported options are DOCKER and FILESYSTEM.
        type: DOCKER

        # Defined key of the agent.
        agent-key: <PROVIDE_ME>

  # Actuator endpoint settings
  info:

    # Reported application name
    app-name: Domino Platform Coordinator

    # Reported application name abbreviation
    abbreviation: DPC
